<?php

/**
 * UsuariosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuariosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsuariosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Usuarios');
    }

    public function buscarPorMail($mail)
    {
    	$q = Doctrine_Query::create()
			->from('Usuarios u') 
			->AndWhere('u.MAIL = ?',$mail);
		$rta = $q->execute()->toArray();
		return $rta;
    }

    public function buscarPorMailPass($mail, $pass)
    {
    	$q = Doctrine_Query::create()
			->from('Usuarios u') 
			->AndWhere('u.MAIL = ?',$mail)
			->AndWhere('u.PASSWORD = ?',$pass);
		$rta = $q->execute()->toArray();
		return $rta;
    }

    public function buscarPorId($id)
    {
        $q = Doctrine_Query::create()
            ->from('Usuarios u') 
            ->AndWhere('u.ID = ?',$id);
        $rta = $q->execute()->toArray();
        return $rta;
    }    
}