<?php

/**
 * AdsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ads');
    }
}