<?php

/**
 * AnimalCategoriesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnimalCategoriesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AnimalCategoriesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AnimalCategories');
    }

    public function getCategories()
    {
    	$q = Doctrine_Query::create()
    		->select('c.*')
    		->from('AnimalCategories');
    	$rta = $q->execute();
    	return $rta->toArray();
    }
}