<?php

/**
 * AnswersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnswersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AnswersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Answers');
    }

    public function post($array)
    {
    	$c = new Answers;
        $c->ANSWER = $array['a'];
        $c->DATE = date('Y-m-d H:i:s');
        $c->USER_ID = $_SESSION['id'];
        $c->save();

        $lm = $c->ID_ANSWER;

        return $lm;
    }
}