<?php

/**
 * CitiesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CitiesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CitiesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cities');
    }
}