<?php

/**
 * CommentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CommentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Comments');
    }

    public function post($array)
    {
    	$c = new Comments;
        $c->COMMENT = $array['comment'];
        $c->DATE = date('Y-m-d H:i:s');
        $c->USER_ID = $_SESSION['id'];
        $c->TRIBUTE_ID = $array['tribute'];
        $c->save();
    }
}