<?php

/**
 * ConversationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConversationsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConversationsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Conversations');
    }
}