<?php

/**
 * ConversationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConversationsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConversationsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Conversations');
    }




    public function getHeaders($to){


/*
				//ESTA CONSULTA EN MYSQL ANDA JOYA
                SELECT u.ID_USER, c.ID_CONVERSATION, u.NICKNAME 
            	FROM conversations c, users u
            	WHERE CASE
            	WHEN c.USER_1_ID = '".$_SESSION['id']."'
            	THEN c.USER_2_ID = u.ID_USER
            	WHEN c.USER_2_ID = '".$_SESSION['id']."'
            	THEN c.USER_1_ID = u.ID_USER
            	END
            	AND (
            		c.USER_1_ID = '".$_SESSION['id']."'
            		or c.USER_2_ID = '".$_SESSION['id']."'
            	)
            	ORDER BY c.ID_CONVERSATION DESC
*/
            	//$this tendria q ser $em pero no sé cómo hacer para instanciar o hacer que $em sea EntityManager
                //http://www.9lessons.info/2013/05/message-conversation-database-design.html

            $q = Doctrine_Query::create()
                ->select("*")
                ->from("Users u")
                ->where("CASE 
                    WHEN c.USER_1_ID = '".$_SESSION['id']."' 
                    THEN c.USER_2_ID = u.ID_USER
                    WHEN c.USER_2_ID = '".$_SESSION['id']."'
                    THEN c.USER_1_ID = u.ID_USER 
                    END
                    ");

            
            $sq = $q->createSubquery()
                ->select("c.*")
                ->from("Conversations c")
                ->AndWhere("c.USER_1_ID = ?", $_SESSION['id'])
                ->orWhere("c.USER_2_ID = ?", $_SESSION['id'])
                ->orderBy("c.ID_CONVERSATION DESC");


            //MASOMENOS DEVUELVE ALGO
            
            /*
            $q = Doctrine_Query::create()
                ->select("u.ID_USER, c.ID_CONVERSATION, u.NICKNAME")
                ->from("Conversations c, c.Users u")
                ->where("CASE 
                    WHEN c.USER_1_ID = '".$_SESSION['id']."' 
                    THEN c.USER_2_ID = u.ID_USER
                    WHEN c.USER_2_ID = '".$_SESSION['id']."'
                    THEN c.USER_1_ID = u.ID_USER 
                    END
                    ");

            
            $sq = $q->createSubquery()
                ->select("c.*")
                ->from("Conversations c")
                ->AndWhere("c.USER_1_ID = ?", $_SESSION['id'])
                ->orWhere("c.USER_2_ID = ?", $_SESSION['id'])
                ->orderBy("c.ID_CONVERSATION DESC");
            */
                

           /* $q = $this->createQuery("
            	SELECT u.ID_USER, c.ID_CONVERSATION, u.NICKNAME 
            	FROM conversations c, users u
            	WHERE CASE
            	WHEN c.USER_1_ID = '".$_SESSION['id']."'
            	THEN c.USER_2_ID = u.ID_USER
            	WHEN c.USER_2_ID = '".$_SESSION['id']."'
            	THEN c.USER_1_ID = u.ID_USER
            	END
            	AND (
            		c.USER_1_ID = '".$_SESSION['id']."'
            		or c.USER_2_ID = '".$_SESSION['id']."'
            	)
            	ORDER BY c.ID_CONVERSATION DESC
            	");
                */
            
            /*
            $q = Doctrine_Query::create()
                ->select("u.ID_USER, c.ID_CONVERSATION, u.NICKNAME")
                ->from("conversations c, c.Users u")
                ->where("CASE 
                    WHEN c.USER_1_ID = '".$_SESSION['id']."' 
                    THEN c.USER_2_ID = u.ID_USER
                    WHEN c.USER_2_ID = '".$_SESSION['id']."'
                    THEN c.USER_1_ID = u.ID_USER 
                    END
                    AND (
                    c.USER_1_ID = '".$_SESSION['id']."'
                    or c.USER_2_ID = '".$_SESSION['id']."'
                )")
                ->orderBy("c.ID_CONVERSATION DESC");

            */
           		
                //ESTA DEBERIA ANDAR PERO NO LA EJECUTA
                /*
                $q = Doctrine_Manager::getInstance()->getCurrentConnection();

                $rta = $q->execute("
                SELECT u.ID_USER, c.ID_CONVERSATION, u.NICKNAME 
                FROM conversations c, users u
                WHERE CASE
                WHEN c.USER_1_ID = '".$_SESSION['id']."'
                THEN c.USER_2_ID = u.ID_USER
                WHEN c.USER_2_ID = '".$_SESSION['id']."'
                THEN c.USER_1_ID = u.ID_USER
                END
                AND (
                    c.USER_1_ID = '".$_SESSION['id']."'
                    or c.USER_2_ID = '".$_SESSION['id']."'
                )
                ORDER BY c.ID_CONVERSATION DESC");
                */

                $rta = $sq->execute();

                $json = array();

                foreach($rta as $m) 
                {

                    $json[] = $m->toArray();
                }

                $rta = json_encode($json);

                return $rta;
    }// End getHeaders
}