<?php

/**
 * CountriesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CountriesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CountriesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Countries');
    }

    public function getCountries()
    {
		
	    $q = Doctrine_Query::create()
			->from('Countries c');

			$country = $q->execute();
			if($country)
				return $country->toArray();
			else
				return false;
	 }



	public function getRegionsByCountry($id){
			
	    $q = Doctrine_Query::create()
			->from('Regions r') 
			->AndWhere('r.CountryID = ?', $id);

			$regions = $q->execute();
			if($regions)
				return $regions->toArray();
			else 
				return false;
	}



	public function getCitiesByRegion($id){
			
	    $q = Doctrine_Query::create()
			->from('Cities c') 
			->AndWhere('c.RegionID = ?', $id);

			$regions = $q->execute();
			if($regions)
				return $regions->toArray();
			else 
				return false;
	}


}