<?php

/**
 * DmasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DmasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DmasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Dmas');
    }
}