<?php

/**
 * FavoritesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FavoritesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FavoritesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Favorites');
    }

    public function addFavorite($ref)
    {
    	$a = new Favorites();
    	$a->ID_USER_ME = $ref['id_user_me'];
    	$a->ID_USER_FAVORITE = $ref['id_user_favorite'];
    	$a->save();

    }

    public function getFavorite($ref){

    	 $q = Doctrine_Query::create()

              ->select('f.ID_USER_FAVORITE') 
              ->from('Favorites f')
              ->where('f.ID_USER_ME= ?', $ref); 
          
          $r = $q->execute();    
          return $r->toArray();
    }


     public function getFavoriteList($ref){

    	 $q = Doctrine_Query::create()

              ->select('u.ID_USER, u.NICKNAME, ph.PIC ') 
              ->from('Users u')
              ->leftJoin('u.Pics ph') 
              ->where('u.ID_USER = ?', $ref) 
               ->groupBy('u.ID_USER');
          
          $r = $q->execute();    
          return $r->toArray();
    }

    public function deleteFavorite($ref){

    	 $q = Doctrine_Query::create()
            ->delete('Favorites f')
            ->where('f.ID_USER_FAVORITE = ?', $ref );
        $q->execute();
    }
}