<?php

/**
 * NbcTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NbcTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NbcTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Nbc');
    }
}