<?php

/**
 * NewsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NewsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NewsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('News');
    }

    public function getNewsByUser($id){ // Ver si puedo hacer estas dos consultas en una sola. Linea 32 y 33 BOusers.php

	        $q = Doctrine_Query::create()
				->from('News n') 
				->AndWhere('n.USER_ID = ?', $id);

			$news = $q->execute();
           
           if(sizeof($news) > 0){
           		return $news->toArray();
           }else{
           		return false;
           }
   }// 
}