<?php

/**
 * OrganizationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrganizationsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrganizationsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Organizations');
    }

    public function insertOrganizations($ref){

    		$Organizations = new Organizations();
            $Organizations->NAME = $ref['name'];
            $Organizations->DESCRIPTION = $ref['description'];
            $Organizations->USER_ID = $ref['user_id'];
            $Organizations->PIC_ID = $ref['pic_id'];

            $Organizations->save();
    }// end insertOrganizations

}