<?php

/**
 * PetsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PetsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PetsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pets');
    }


    public function getPetListByUser($id)
    {
        $q = Doctrine_Query::create()
            ->select('p.ID_PET, p.NAME, p.BREED, p.PIC_ID')
            ->from('Pets p') 
            ->AndWhere('p.USER_ID = ?',$id);
        $rta = $q->execute(); //devuelvo el objeto doctrine
        
        return $rta;
    }

    public function getPetsByUser($id)
    {
    	$q = Doctrine_Query::create()
			->from('Pets p') 
			->AndWhere('p.USER_ID = ?',$id);
		$rta = $q->execute(); //devuelvo el objeto doctrine
		
		return $rta;
    }

}