<?php

/**
 * PicsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PicsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PicsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pics');
    }
}