<?php

/**
 * PrivateaddressesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PrivateaddressesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PrivateaddressesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Privateaddresses');
    }
}