<?php

/**
 * ProxynetworksTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProxynetworksTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProxynetworksTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Proxynetworks');
    }
}