<?php

/**
 * QasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Qas');
    }
}