<?php

/**
 * SubnetsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubnetsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SubnetsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Subnets');
    }
}