<?php

/**
 * TributesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TributesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TributesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tributes');
    }

    public function createTribute($array)
    {
    	var_dump($array);
    	$t = new Tributes;
    	$t->TITLE = $array['tr-title'];
    	$t->CONTENT = $array['tr-msg'];

    	if(!empty($array['tr-since']))
    		$t->SINCE = $array['tr-since'];
    	if(!empty($array['tr-thru']))
    		$t->THRU = $array['tr-thru'];
    	
    	$t->USER_ID = $array['u'];
    	$t->PET_ID = $array['p'];

    	$t->save();
    	return $t->ID_TRIBUTE;
    }

    public function getTribute($id)
    {
    	$q = Doctrine_Query::create()
    		->from('Tributes t')
    		->where('t.ID_TRIBUTE = ?', $id);
    	$r = $q->execute();
    	return $r->toArray();

    }

    public function getTributeByPet($id)
    {
        $q = Doctrine_Query::create()
            ->from('Tributes')
            ->where('PET_ID =?',$id);

        $r = $q->execute();
        return $r->toArray();
    }
}