<?php

/**
 * VetTalkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VetTalkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VetTalkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VetTalk');
    }
}