<?php

/**
 * VideosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VideosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VideosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Videos');
    }

    
   public function upload($ref){

            $now = date('Y-m-d');

            $Videos = new Videos();
            $Videos->VIDEO = $ref['video'];
            $Videos->TITLE = $ref['title'];
            $Videos->CAPTION = $ref['caption'];
            $Videos->THUMBNAIL = $ref['thumbnail']; 
            $Videos->DATE = $now;
            $Videos->PET_ID = $ref['pet_id'];

            $Videos->save();
   }// end upload_img

       

    public function getVideosList()
    {
        $q = Doctrine_Query::create()
            ->select('v.THUMBNAIL, v.CAPTION, v.TITLE, v.VIDEO')
            ->from('Videos v');
        
        $r = $q->execute();    
        if($r)
            return $r->toArray();
        else
            return false;
    }

     
/*
     public function getVideosByCategory($id)
    {
        $q = Doctrine_Query::create()

            ->select('p.ID_PET, p.ANIMAL_CATEGORY_ID, p.NAME, v.THUMBNAIL, v.CAPTION, v.TITLE, v.VIDEO')
            ->from('Pets p')
            ->innerJoin('p.Videos v')
            ->where('p.ANIMAL_CATEGORY_ID = ?', $id);

        

        $r = $q->execute();    
        if($r)
            return $r->toArray();
        else
            return false;

    }

     public function getVideosRamdom() // revisar esta funcion pq no me queda claro q carajo me trae, aunque anda
    {      
        $userCount = Doctrine::getTable('Videos')->count();
        $user = Doctrine::getTable('Videos')
       ->createQuery()
       //->limit(2)
       ->offset(rand(0, $userCount - 1))
       ->fetchOne();


       if($user)
        return $user->toArray();
       else
        return false;

    }
*/


     public function getVideosByPet($id)
     { // Ver si puedo hacer estas dos consultas en una sola. Linea 32 y 33 BOusers.php

            $q = Doctrine_Query::create()
    			->from('Videos v') 
    			->AndWhere('v.PET_ID = ?', $id);

    		$videos = $q->execute();

            if($videos)
           		return $videos->toArray();
            else
                return false;
          
     } 
/*
        public function howmuch_videos(){

           $Count = Doctrine::getTable('Videos')->count();    
           return $Count;

        }

*/
     
}
