<?php

/**
 * VideosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VideosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VideosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Videos');
    }

    
    public function upload($ref){

            $now = date('Y-m-d');

            $Videos = new Videos();
            $Videos->VIDEO = $ref['video'];
            $Videos->TITLE = $ref['title'];
            $Videos->CAPTION = $ref['caption'];
            $Videos->THUMBNAIL = $ref['thumbnail']; 
            $Videos->DATE = $now;
            $Videos->PET_ID = null;

            $Videos->save();
   }// end upload_img

        public function getVideosList()
    {
        $q = Doctrine_Query::create()
            //->select('p.USER_ID, u.ID_USER, u.NAME, u.LASTNAME, u.NICKNAME, ph.PIC, k.Country, r.Region, c.City')
            ->select('v.THUMBNAIL, v.CAPTION, v.TITLE, v.VIDEO')
            ->from('Videos v');
            //->innerJoin('p.Users u')
           // ->leftJoin('u.Pics ph') // van con leftJoin, sino, si el usuario no tiene nada cargado, no trae nada
            //->leftJoin('u.Countries k')
            //->leftJoin('u.Regions r')
            //->leftJoin('u.Cities c')
            //->where('p.ANIMAL_CATEGORY_ID = ?', $id)
           // ->groupBy('u.ID_USER');
        
        $r = $q->execute();    
        
        return $r->toArray();
    }

    public function getVideosByPet($id)
    { // Ver si puedo hacer estas dos consultas en una sola. Linea 32 y 33 BOusers.php

        $q = Doctrine_Query::create()
			->from('Videos v') 
			->AndWhere('v.PET_ID = ?', $id);

		$videos = $q->execute();
       
       if(sizeof($videos) > 0){
       		return $videos->toArray();
       }else{
       		return false;
       }
   } 
}