<?php

/**
 * ZadAdsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ZadAdsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ZadAdsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ZadAds');
    }
}