<?php

/**
 * ZadImpressionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ZadImpressionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ZadImpressionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ZadImpressions');
    }
}