<?php

/**
 * ZadImagesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ZadImagesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ZadImagesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ZadImages');
    }
}