DROP DATABASE IF EXISTS pet_magick;
CREATE DATABASE pet_magick;
USE pet_magick;

/*COMENTARIOS:
Protocolo(?)
-Tablas en plural, minuscula
-Columnas en singular, mayuscula (salvo news pq es asi de movida)
-IDs de tablas ID_ + "nombre de tabla en sigunlar" (ej. ID_CITY)
-FK "nombre de tabla" + _ID (ej. CITY_ID)
-Guion bajo para cuando son dos palabras (ej. animal_categories)
-Picture siempre lo abrevie como pic pq me gusta no se
=====


Chequear bien los largos de los varchar evaluar si se necesita cambiar alguno a text
Chequear los not null
Chequear los char (son las url)

Estaba pensando en agregar un campo DATE en todas las tablas. cosa q si despues necesitamos filtrar algo este la opcion de la fecha. total es una gilada agregarlo, no sé q pensas
*/

/* ---------------- */
CREATE TABLE countries(
	ID_COUNTRY INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
	COUNTRY VARCHAR(45) NOT NULL
);

/* ---------------- */
CREATE TABLE cities(
	ID_CITY INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
	CITY VARCHAR(45) NOT NULL,
	COUNTRY_ID INT UNSIGNED NOT NULL,

	FOREIGN KEY(COUNTRY_ID) REFERENCES countries(ID_COUNTRY)
);

/* ---------------- */
CREATE TABLE albums(
	ID_ALBUM INT UNSIGNED PRIMARY KEY AUTO_INCREMENT
);

/* ---------------- */
CREATE TABLE pics(
	ID_PIC INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
	PIC VARCHAR(100) NOT NULL,
	DATE DATE NOT NULL,
	CAPTION VARCHAR(100), 
	THUMBNAIL INT UNSIGNED NOT NULL,
	ALBUM_ID INT UNSIGNED,
	FOREIGN KEY(THUMBNAIL) REFERENCES pics(ID_PIC),
	FOREIGN KEY(ALBUM_ID) REFERENCES albums(ID_ALBUM)
);

/* ---------------- */
CREATE TABLE users(
	ID_USER INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
	NAME VARCHAR(45) NOT NULL,
	LASTNAME VARCHAR(45) NOT NULL,
	NICKNAME VARCHAR(45) NOT NULL UNIQUE,
	EMAIL VARCHAR(45) NOT NULL UNIQUE,
	PASSWORD CHAR(40) NOT NULL,
	ABOUT VARCHAR(45),
	PIC_ID INT UNSIGNED, /*Foto de perfil q es una relacion directa entre user y pics*/
	ALBUM_ID INT UNSIGNED, /*fotos subidas al album q es la relacion entre users y albums*/
	RANK TINYINT(1) UNSIGNED NOT NULL, /* Aca probe de todo y solo funciono cuando cambie RANGE x RANGO. Parece ser q el problema es el nombre, raro... */
	CITY_ID INT UNSIGNED NOT NULL,
	TOKEN CHAR(40) UNSIGNED,
	
	FOREIGN KEY(PIC_ID) REFERENCES pics(ID_PIC),
	FOREIGN KEY(ALBUM_ID) REFERENCES albums(ID_ALBUM),
	FOREIGN KEY(CITY_ID) REFERENCES cities(ID_CITY)
);

/* ---------------- */
CREATE TABLE animal_categories(
	ID_ANIMAL_CATEGORY INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
	NAME VARCHAR(45) NOT NULL
);

/* ---------------- */
CREATE TABLE pets(
	ID_PET INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
	NAME VARCHAR(45) NOT NULL,
	BREED VARCHAR(45),
	TRAITS VARCHAR(100),
	STORY VARCHAR(300),
	USER_ID INT UNSIGNED NOT NULL,
	ANIMAL_CATEGORY_ID INT UNSIGNED NOT NULL,
	PIC_ID INT UNSIGNED, /*FOTO DE PERFIL*/
	ALBUM_ID INT UNSIGNED, /*album de fotos*/

	FOREIGN KEY(USER_ID) REFERENCES users(ID_USER),
	FOREIGN KEY(ANIMAL_CATEGORY_ID) REFERENCES animal_categories(ID_ANIMAL_CATEGORY),
	FOREIGN KEY(PIC_ID) REFERENCES pics(ID_PIC),
	FOREIGN KEY(ALBUM_ID) REFERENCES albums(ID_ALBUM)
);

/* ---------------- */
CREATE TABLE tributes(
	ID_TRIBUTE INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
	TITLE VARCHAR(100) NOT NULL,
	CONTENT TEXT NOT NULL,
	NAME VARCHAR(45) NOT NULL,
	BREED VARCHAR(45),
	SINCE DATE NOT NULL,
	THRU DATE NOT NULL, /* Aca probe de todo y solo funciono cuando cambie TO x HASTA. Parece ser q el problema es el nombre, raro... */
	PIC_ID INT UNSIGNED, 
	USER_ID INT UNSIGNED NOT NULL,
	PET_ID INT UNSIGNED, 

	FOREIGN KEY(PIC_ID) REFERENCES pics(ID_PIC),
	FOREIGN KEY(USER_ID) REFERENCES users(ID_USER),
	FOREIGN KEY(PET_ID) REFERENCES pets(ID_PET)
);

/* ---------------- */
CREATE TABLE vet_talk(
	ID_VET_TALK INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
	TITLE VARCHAR(100) NOT NULL,
	CONTENT TEXT NOT NULL,
	DATE DATE NOT NULL,
	USER_ID INT UNSIGNED NOT NULL,
	PIC_ID INT UNSIGNED, 

	FOREIGN KEY(USER_ID) REFERENCES users(ID_USER),
	FOREIGN KEY(PIC_ID) REFERENCES pics(ID_PIC)
);

/* ---------------- */
CREATE TABLE qas(
	ID_QA INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
	QUESTION TEXT NOT NULL,
	ANSWER TEXT,
	DATE DATE NOT NULL,
	USER_ID INT UNSIGNED NOT NULL,
	VET_ID INT UNSIGNED,
	
	FOREIGN KEY(USER_ID) REFERENCES users(ID_USER),
	FOREIGN KEY(VET_ID) REFERENCES users(ID_USER)
);

/* ---------------- */ 
CREATE TABLE news(
	ID_NEWS INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
	NEWS VARCHAR(300) NOT NULL,
	DATE DATE NOT NULL,
	USER_ID INT UNSIGNED NOT NULL,

	FOREIGN KEY(USER_ID) REFERENCES users(ID_USER)
);

/* ---------------- */
CREATE TABLE organizations(
	ID_ORGANIZATION INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
	NAME VARCHAR(100) NOT NULL, 
	DESCRIPTION TEXT NOT NULL,
	USER_ID INT UNSIGNED NOT NULL,
	PIC_ID INT UNSIGNED, 

	FOREIGN KEY(USER_ID) REFERENCES users(ID_USER),
	FOREIGN KEY(PIC_ID) REFERENCES pics(ID_PIC)
);

/* ---------------- */
CREATE TABLE blogs(
	ID_BLOG INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
	TITLE VARCHAR(100) NOT NULL,
	CONTENT TEXT NOT NULL,
	DATE DATE NOT NULL,
	USER_ID INT UNSIGNED NOT NULL,
	PIC_ID INT UNSIGNED, 

	FOREIGN KEY(USER_ID) REFERENCES users(ID_USER),
	FOREIGN KEY(PIC_ID) REFERENCES pics(ID_PIC)
);

/* ---------------- */
CREATE TABLE projects(
	ID_PROJECT INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
	TITLE VARCHAR(100) NOT NULL,
	DESCRIPTION TEXT NOT NULL,
	USER_ID INT UNSIGNED NOT NULL,
	ALBUM_ID INT UNSIGNED,

	FOREIGN KEY(USER_ID) REFERENCES users(ID_USER),
	FOREIGN KEY(ALBUM_ID) REFERENCES albums(ID_ALBUM)
);

/* ---------------- */
CREATE TABLE videos(
	ID_VIDEO INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
	VIDEO CHAR(30) NOT NULL,
	TITLE VARCHAR(100) NOT NULL,
	CAPTION VARCHAR(300) NOT NULL,
	THUMBNAIL CHAR(30) NOT NULL,
	DATE DATE NOT NULL,
	PET_ID INT UNSIGNED,

	FOREIGN KEY(PET_ID) REFERENCES pets(ID_PET)
);

/* ---------------- */ /*INBOX*/
CREATE TABLE messages(
	ID_MESSAGE INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
	FROM_USER_ID INT UNSIGNED NOT NULL,
	TO_USER_ID INT UNSIGNED NOT NULL,
	SUBJECT VARCHAR(100) NOT NULL,
	MESSAGE TEXT,
	STATUS TINYINT(1) NOT NULL,
	DATE DATE NOT NULL,

	FOREIGN KEY(FROM_USER_ID) REFERENCES users(ID_USER),
	FOREIGN KEY(TO_USER_ID) REFERENCES users(ID_USER)
);

/* ---------------- */ 
CREATE TABLE ads(
	ID_AD INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
	AD CHAR(30) NOT NULL,
	LINK INT UNSIGNED NOT NULL,
	DATE DATE NOT NULL,
	DATE_FROM DATE,
	DATE_TO DATE,
	STATUS TINYINT(1) NOT NULL
);

/* ---------------- */ 
CREATE TABLE comments(
	ID_COMMENT INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
	COMMENT VARCHAR(300) NOT NULL, /* Aca tenias un UNSIGNED en un tipo de dato texto */
	DATE DATE NOT NULL,
	USER_ID INT UNSIGNED NOT NULL,
	TRIBUTE_ID INT UNSIGNED,

	FOREIGN KEY(USER_ID) REFERENCES users(ID_USER),
	FOREIGN KEY(TRIBUTE_ID) REFERENCES tributes(ID_TRIBUTE)
);
